appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: 0L1FKLuhlwYPCEaQ9IAub878ZdoOjhvFij6kMDtsbeKp/Sy/PtJ8q4CwIoYEdwP5dk2yjGwTXskix8KVFsa8N4TF1YwBy5MUgEtEt47G7hfMbfKiF0jUKAU0HGWT+tus2OPNokIu8UEBwa006sEhsldbP5Wknd4MKzQpH8W67J2jo1aGDAuhh+lgmEC3IQfAJOiN93M0h2DX11TKFLaoKBtZMK6SHigLv6MR+PSgXHRSBbfMiNvjj4enDEN0BLkphS8Ni17OVirrssmrsp5AIBRMbWynrKs6eouYmD6N0Qooil40mUIUqa2O7IDlFH2l9tBXthePuK36gMZldH3HpGihvVv3/V9X46VFEQKJn0dMYz48uilizU+158VP4tkWg9i2nx98/frIsBYeSI+wZYyvONts+pm8Hxktli24dbkJsncYLb66ij7SK/7LAhTYlXZWLfVGiyTwVJAZJL4dX3CUNhzamU4QyAybvcs9bzLmkLtyLGgjwSGg5dnZmc2HuwUEuTtFZeLuYsUFfjzTQJKMLd03yguLz1y5bEQsp0NnIjO5cTNdoDhP+8nCLFMVH0685Pd32jHaJ6MV9HtAjhf5f/JB9P+21RYyrZKCcSzCs1yJJpnOlPUHFDwX65Wl2/ddI3TupJ9ZTgBcYcYQtMF9Y6TJoHviP65Mdd1awGI=}
